name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout master"
        uses: actions/checkout@v2
      
      - name: "Build image"
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest .
        
      - name: "Login in docker"
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: "Push in remote repo"
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
    
  
  deploy: 
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: "Connecting host"
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH }}
          script: |
            ls
