name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout master"
        uses: actions/checkout@v2
        
      - name: "aboba"
        run: ls
      
      - name: "Build image"
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest .
        
      - name: "Login in docker"
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: "Push in remote repo"
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
    
  deploy: 
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: "Connecting host and start app"
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH }}
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
            # docker stop ${{ secrets.CONTAINER_NAME }}
            # docker rm ${{ secrets.CONTAINER_NAME }}
            # docker run --restart always --publish 8080:8080 --name ${{ secrets.CONTAINER_NAME }} \
            # ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
            # docker ps -a
